name: EyeTism
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - dlib=19.24.2
  - imageio=2.34.0
  - ipywidgets=8.1.2
  - jupyterlab=4.1.5
  - lightgbm=4.3.0
  - matplotlib=3.8.3
  - numpy=1.26.4
  - opencv-contrib-python=4.9.0.80
  - pandas=2.2.1
  - pip
  - python=3.11.3
  - pytorch=2.2.2
  - scikit-image=0.22.0
  - scikit-learn=1.4.1.post1
  - seaborn=0.13.2
  - streamlit=1.33.0
  - torchvision=0.17.2
  - tqdm=4.66.2
  - xgboost=2.0.3
  - pip:
    - face-recognition==1.3.0
    - mediapipe==0.10.9
    - tensorflow==2.16.1